=== FanteyOfficial/CompitoTPSI-5IA/ScuoleMaterne.dtd
<!ELEMENT ScuoleMaterne (ScuolaMaterna*)>
<!ELEMENT ScuolaMaterna (Nome, Comune, Provincia, Regione, AnnoInserimento, DataOraInserimento, Longitudine, Latitudine)>
<!ATTLIST ScuolaMaterna identificatoreInOpenStreetMap CDATA #REQUIRED>
<!ELEMENT Nome (#PCDATA)>
<!ELEMENT Comune (#PCDATA)>
<!ELEMENT Provincia (#PCDATA)>
<!ELEMENT Regione (#PCDATA)>
<!ELEMENT AnnoInserimento (#PCDATA)>
<!ELEMENT DataOraInserimento (#PCDATA)>
<!ELEMENT Longitudine (#PCDATA)>
<!ELEMENT Latitudine (#PCDATA)>

=== FanteyOfficial/CompitoTPSI-5IA/ScuoleMaterne.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<?xml-stylesheet type="text/xsl" href="ScuoleMaterne.xsl"?>
<!DOCTYPE ScuoleMaterne SYSTEM "ScuoleMaterne.dtd">

<ScuoleMaterne>
    <ScuolaMaterna identificatoreInOpenStreetMap="257543657">
        <Nome>Asilo Comunale di Pieve di Sinalunga</Nome>
        <Comune codiceComune="52033">
            <Classe nome="Lorenzo_1">5IA</Classe>
        </Comune>
        <Provincia>52</Provincia>
        <Regione>9</Regione>
        <AnnoInserimento>2008</AnnoInserimento>
        <DataOraInserimento>2008-04-14T13:44:53Z</DataOraInserimento>
        <Longitudine>11.741567</Longitudine>
        <Latitudine>43.2160801</Latitudine>
    </ScuolaMaterna>
    <ScuolaMaterna identificatoreInOpenStreetMap="354540218">
        <Nome>Muzio Gallo</Nome>
        <Comune codiceComune="42034">
            <Classe nome="Lorenzo_2">5IA</Classe>
        </Comune>
        <Provincia>42</Provincia>
        <Regione>11</Regione>
        <AnnoInserimento>2009</AnnoInserimento>
        <DataOraInserimento>2009-03-07T20:15:55Z</DataOraInserimento>
        <Longitudine>13.4768942</Longitudine>
        <Latitudine>43.4841404</Latitudine>
    </ScuolaMaterna>
    <ScuolaMaterna identificatoreInOpenStreetMap="321846083">
        <Nome>Santelli</Nome>
        <Comune codiceComune="49009">
            <Classe nome="Lorenzo_3">5IA</Classe>
        </Comune>
        <Provincia>49</Provincia>
        <Regione>9</Regione>
        <AnnoInserimento>2011</AnnoInserimento>
        <DataOraInserimento>2011-10-28T14:35:10Z</DataOraInserimento>
        <Longitudine>10.3153373</Longitudine>
        <Latitudine>43.5583449</Latitudine>
    </ScuolaMaterna>
    <ScuolaMaterna identificatoreInOpenStreetMap="672982844">
        <Nome>Scuola Attiva</Nome>
        <Comune codiceComune="58091">
            <Classe nome="Lorenzo_4">5IA</Classe>
        </Comune>
        <Provincia>58</Provincia>
        <Regione>12</Regione>
        <AnnoInserimento>2013</AnnoInserimento>
        <DataOraInserimento>2013-03-01T11:40:18Z</DataOraInserimento>
        <Longitudine>12.5371053</Longitudine>
        <Latitudine>41.9441825</Latitudine>
    </ScuolaMaterna>
</ScuoleMaterne>
